/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.controller;

import java.io.IOException;

import org.springframework.http.ResponseEntity;
import org.springframework.http.ResponseEntity.BodyBuilder;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import twitter4j.TwitterException;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-17T23:34:46.447Z")

@Api(value = "users", description = "the users API")
public interface UsersApi {

	@ApiOperation(value = "", nickname = "pcTest", notes = "", response = BodyBuilder.class, tags = {})
	@ApiResponses(value = { @ApiResponse(code = 200, message = "successful operation", response = BodyBuilder.class) })
	@RequestMapping(value = "/mouseListener", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<ResponseDTO> mouseListener() throws IOException, TwitterException, InterruptedException, Exception;
	
}
